server:
  port: 9001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.7.22:3306/networkProgram?useUnicode=true&characterEncoding=utf8
    username: root
    password: 555250

mybatis-plus:
  type-aliases-package: com.gd.network.command.model.pojo
  configuration:
    map-underscore-to-camel-case: false